#! /usr/bin/env python3
import rospy

from topic_task.msg import slang
import random


rospy.init_node('_publisher', anonymous=True)

pub=rospy.Publisher('/slang_topic',slang, queue_size=10)

rate=rospy.Rate(1)

i=0
while not rospy.is_shutdown():
    slang= slang()
   
    slang.name="Hi this is name string "
   

    rospy.loginfo("Information Published")
    pub.publish(slang)
    rate.sleep()
    i=i+1
